apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-api
  namespace: monitoring
  labels:
    app: agent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-api
  template:
    metadata:
      labels:
        app: agent-api
    spec:
      serviceAccountName: opentelemetrycollector
      containers:
      - name: agent-api
        image: ants-registry.inf.um.es/telemetry/plugin-api-otel:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /tmp
            name: version-storage
      volumes:
        - name: version-storage
          emptyDir: {}
