apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agent-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent-api
    spec:
      serviceAccountName: opentelemetrycollector
      containers:
        - name: agent-api
          image: ants-registry.inf.um.es/telemetry/plugin-api-otel:latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 8000